# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.CharField(max_length=500),
        ),
    ]
